-- AlterTable
ALTER TABLE "Loans" ALTER COLUMN "LoanTerm" DROP NOT NULL,
ALTER COLUMN "LoanStartDate" DROP NOT NULL,
ALTER COLUMN "RemainingTenure" DROP NOT NULL,
ALTER COLUMN "RemainingTenure" SET DEFAULT 360,
ALTER COLUMN "LoanStatus" DROP NOT NULL;
